name: self_service_api
description: SelfService application API
dependencies:
    angular: any
    browser: any
    js: any
    shadow_dom: any
    unittest: any
    route: any
    json_object: any
    mongo_dart: any
    http: any
    dart_jwt: ">=0.1.2 <0.2.0"
    logging: ">=0.9.2 <0.10.0"


